# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: test.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'test.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ntest.proto\x12\x04test\"$\n\x11UnaryUnaryRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\"%\n\x12UnaryUnaryResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2P\n\x0bTestService\x12\x41\n\nUnaryUnary\x12\x17.test.UnaryUnaryRequest\x1a\x18.test.UnaryUnaryResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'test_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_UNARYUNARYREQUEST']._serialized_start=20
  _globals['_UNARYUNARYREQUEST']._serialized_end=56
  _globals['_UNARYUNARYRESPONSE']._serialized_start=58
  _globals['_UNARYUNARYRESPONSE']._serialized_end=95
  _globals['_TESTSERVICE']._serialized_start=97
  _globals['_TESTSERVICE']._serialized_end=177
# @@protoc_insertion_point(module_scope)
