repos:
-   repo: https://github.com/pycqa/isort
    rev: 5.7.0
    hooks:
    -   id: isort
-   repo: local
    hooks:
    -   id: black
        name: black
        entry: black --check
        language: system
        types: [python]
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4
    hooks:
    -   id: flake8
        exclude: elasticapm\/utils\/wrapt|build|src|tests|dist|conftest.py|setup.py
-   repo: local
    hooks:
    -   id: license-header-check
        name: License header check
        description: Checks the existance of license headers in all Python files
        entry: ./tests/scripts/license_headers_check.sh
        exclude: "(elasticapm/utils/wrapt/.*|tests/utils/stacks/linenos.py|tests/utils/stacks/linenos2.py)"
        language: script
        types: [python]
