repos:
# seed-isort-config disabled for now, see https://github.com/asottile/seed-isort-config/issues/10
#-   repo: https://github.com/asottile/seed-isort-config
#    rev: v1.1.0
#    hooks:
#    -   id: seed-isort-config
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.21
    hooks:
    -   id: isort
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    -   id: black
        language_version: python3
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: flake8
        exclude: elasticapm\/utils\/wrapt|build|src|tests|dist|conftest.py|setup.py
-   repo: local
    hooks:
    -   id: license-header-check
        name: License header check
        description: Checks the existance of license headers in all Python files
        entry: ./tests/scripts/license_headers_check.sh
        exclude: "(elasticapm/utils/wrapt/.*|tests/utils/stacks/linenos.py|tests/utils/stacks/linenos2.py)"
        language: script
        types: [python]
