repos:
-   repo: https://github.com/pycqa/isort
    rev: 5.5.4
    hooks:
    -   id: isort
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    -   id: black
        language_version: python3
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: flake8
        exclude: elasticapm\/utils\/wrapt|build|src|tests|dist|conftest.py|setup.py
-   repo: local
    hooks:
    -   id: license-header-check
        name: License header check
        description: Checks the existance of license headers in all Python files
        entry: ./tests/scripts/license_headers_check.sh
        exclude: "(elasticapm/utils/wrapt/.*|tests/utils/stacks/linenos.py|tests/utils/stacks/linenos2.py)"
        language: script
        types: [python]
