sudo: false
language: python
python:
- 2.7
- 3.3
- 3.4
- 3.5
- 3.6
- nightly
- pypy

env:
  matrix:
    - WEBFRAMEWORK=django-1.8
    - WEBFRAMEWORK=django-1.9
    - WEBFRAMEWORK=django-1.10
    - WEBFRAMEWORK=django-1.11
    - WEBFRAMEWORK=django-master
    - WEBFRAMEWORK=flask-0.10
    - WEBFRAMEWORK=flask-0.11
    - WEBFRAMEWORK=flask-0.12
  global:
  - PIP_CACHE="$HOME/.pip_cache"'
  - RUN_SCRIPT="./travis/run_tests.sh"
matrix:
  exclude:
  - python: 2.7
    env: WEBFRAMEWORK=django-master
  - python: 3.3
    env: WEBFRAMEWORK=django-1.9
  - python: 3.3
    env: WEBFRAMEWORK=django-1.10
  - python: 3.3
    env: WEBFRAMEWORK=django-1.11
  - python: 3.3
    env: WEBFRAMEWORK=django-master
  include:
  - sudo: required
    python: 3.4
    services:
    - docker
    env: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64 RUN_SCRIPT=./travis/run_docker.sh
  - sudo: required
    python: 3.4
    services:
    - docker
    env: DOCKER_IMAGE=quay.io/pypa/manylinux1_i686 RUN_SCRIPT=./travis/run_docker.sh
      PRE_CMD=linux32
  allow_failures:
  - env: WEBFRAMEWORK=django-master
  - python: nightly
addons:
  apt:
    sources:
     - mongodb-3.0-precise
    packages:
     - libevent-dev
     - libzmq3-dev
     - mongodb-org-server
  postgresql: '9.4'
cache:
  directories:
  - "$HOME/.pip_cache"
script:
- bash $RUN_SCRIPT
notifications:
  email: false
  slack:
    secure: LcTTbTj0Px0/9Bs/S/uwbhkdULlj1YVdHnU8F/kOa3bq2QdCTptqB719r6BnzHvW+QGyADvDZ25UncVXFuLuHY67ZYfmyZ/H2cj0nrRSuYdPct0avhVbT/3s50GlNWK5qkfZDuqw6szYTFrgFWJcr5dl7Zf6Vovcvd38uaYOdno=
services:
  - redis-server
  - memcached
  - mongodb
  - mysql
  - postgresql
deploy:
  provider: s3
  access_key_id: AKIAIHY7VOHA6YNCCEYQ
  secret_access_key:
    secure: kb8Ho6JjTi3yTtdppw+fk6Zka0TLrFuEZU+O/b1YP4GEWUcf/aFKwtE8hi4SvsnjHGZxrAY9jRHKjVU02eEfbUTrCGu05ej9wEVC8IhevJMJljgInHWsG1PgPtNeD+uxWADXSXddjJ0U+N3Gh3I/PO530te2V2rQ1szJ2Hq79go=
  bucket: wheels.opbeat.com
  skip_cleanup: true
  local_dir: wheelhouse
  acl: public_read
  on:
    repo: opbeat/opbeat_python
    tags: true
