// Use these for links to issue and pulls. Note issues and pulls redirect one to
// each other on Github, so don't worry too much on using the right prefix.
:issue: https://github.com/elastic/apm-agent-python/issues/
:pull: https://github.com/elastic/apm-agent-python/pull/

[[changelog]]
== Changelog


[[release-next]]
[float]
=== Unreleased
https://github.com/elastic/apm-agent-python/compare/v1.0.0\...master[Check the HEAD diff]

 * moved the library-frame detection from a processor to the stacktrace collection ({pull}113[#113]).
 * added settings to enable/disable source code collection and local variables collection
   for errors and transactions ({pull}117[#117])
 * BREAKING: Several settings and APIs have been renamed ({pull}111[#111], {pull}119[#119]):
 ** The decorator for custom instrumentation, `elasticapm.trace`, is now `elasticapm.capture_span`
 ** The setting `traces_send_frequency` has been renamed to `transaction_send_frequency`.
     The name of the analogous environment variable changed from `ELASTIC_APM_TRACES_SEND_FREQ`
     to `ELASTIC_APM_TRANSACTION_SEND_FREQ`
 ** The `app_name` setting has been renamed to `service_name`.
     The name of the analogous environment variable changed from `ELASTIC_APM_APP_NAME`
     to `ELASTIC_APM_SERVICE_NAME`.
 ** `app_name` arguments to API calls in the whole code base changed to `service_name`.
 ** `context.request.url.raw` has been renamed to `context.request.url.full` ({pull}121[#121])

[[release-1.0.0]]
[float]
=== v1.0.0
https://github.com/elastic/apm-agent-python/compare/v1.0.0.dev3\...v1.0.0[Check the HEAD diff]

 * added `max-event-queue-length` setting. ({pull}67[#67])
 * changed name that the agent reports itself with to the APM server from `elasticapm-python` to `python`. This aligns the Python agent with other languages. ({pull}104[#104])
 * changed Celery integration to store the task state (e.g. `SUCCESS` or `FAILURE`) in `transaction.result` ({pull}100[#100])
 * added setting to disable SSL certificate verification ({pull}108[#108])
 * BREAKING: renamed `server` configuration variable to `server_url` to better align with other language agents ({pull}105[#105]) 
 * BREAKING: removed the old and unused urllib2-based HTTP transport, and renamed the urllib3 transport ({pull}107[#107])
 * BREAKING: several API changes to `capture_exception`, `capture_message`, and added documentation for these and other APIs ({pull}112[#112])

[[release-v1.0.0.dev3]]
[float]
=== v1.0.0.dev3

https://github.com/elastic/apm-agent-python/compare/v1.0.0.dev2\...v1.0.0.dev2[Check the diff]


 * added a background thread to process the transactions queue every 60 seconds (configurable) ({pull}68[#68])
 * adapted trace context for SQL traces to new API ({pull}77[#77])
 * ensured that transaction data is also passed through processors ({pull}84[#84])
 * added `uninstrument` function to reverse instrumentation,
   and exposed both `instrument` and `uninstrument` as public API in the `elasticapm` namespace  ({pull}90[#90])
 * added normalization of HTTP status codes into classes for the `transaction.result` field. A HTTP status of `200`
   will be turned into `HTTP 2xx`. The unchanged status code is still available in `context.response.status_code`.
   ({pull}85[#85])


[[release-v1.0.0.dev2]]
[float]
=== v1.0.0.dev2

https://github.com/elastic/apm-agent-python/compare/v1.0.0.dev1\...v1.0.0.dev2[Check the diff]

 * added request context information for Flask ({pull}58[#58])
 * added response context information for Flask ({pull}65[#65])
 * BREAKING: changed the `SERVERS` list setting to a single `SERVER` string setting.
   With this change, we now only support sending events to a single server ({pull}59[#59])
 * BREAKING: removed root trace. Due to historical reason, we used to create a "root trace" which was equivalent
   to the transaction. This is no longer necessary. {pull}61[#61]

[[release-v1.0.0.dev1]]
[float]
=== v1.0.0.dev1

https://github.com/elastic/apm-agent-python/compare/v1.0.0.dev0\...v1.0.0.dev1[Check the diff]

 * unified configuration across supported frameworks ({pull}33[#33])
 * added in-app frame detection ({pull}36[#36])
 * added tagging functionality ({pull}28[#28])
 * preliminary support for Django 2.0 ({pull}26[#26])
 * initial set of documentation

[[release-v1.0.0.dev0]]
[float]
=== v1.0.0.dev0

First release of the Python agent for Elastic APM
