version: '2.1'

services:
  postgres:
    user: postgres
    image: postgres
    ports: 
      - "5432:5432"
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_DB: 'elasticapm_test'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 30s
      retries: 3

  mongodb:
    image: mongo
    ports: 
      - "27017:27017"

  memcached:
    image: memcached
    ports: 
      - "11211:11211"

  redis:
    image: redis
    ports: 
      - "6397:6397"

  run_tests:
    build: 
      context: .
      dockerfile: Dockerfile
    environment: 
      MONGODB_HOST: 'mongodb'
      REDIS_HOST: 'redis'
      MEMCACHED_HOST: 'memcached'
      POSTGRES_USER: 'postgres'
      POSTGRES_DB: 'elasticapm_test'
      POSTGRES_HOST: 'postgres'
      POSTGRES_PORT: '5432'
    depends_on:
      postgres:
        condition: service_healthy 
      mongodb:
        condition: service_started
      memcached:
        condition: service_started
      redis:
        condition: service_started
