---

name: common package tasks
description: Run the packages

runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38 # v5
      with:
        python-version: "3.10"
    - name: Override the version if there is no tag release.
      run: |
        if [[ "${GITHUB_REF}" != refs/tags/* ]]; then
          echo "ELASTIC_CI_POST_VERSION=${{ github.run_id }}" >> "${GITHUB_ENV}"
        fi
      shell: bash
    - name: Build packages
      run: ./dev-utils/make-packages.sh
      shell: bash
    - name: Upload Packages
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
      with:
        name: packages
        path: |
          dist/*.whl
          dist/*tar.gz
