---

name: common build distribution tasks
description: Run the build distribution

runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38 # v5
      with:
        python-version: "3.10"

    - name: Build lambda layer zip
      run: ./dev-utils/make-distribution.sh
      shell: bash

    - uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1 # v4
      with:
        name: build-distribution
        path: ./build/
        if-no-files-found: error
