---

name: common build distribution tasks
description: Run the build distribution

runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Build lambda layer zip
      run: ./dev-utils/make-distribution.sh
      shell: bash

    - uses: actions/upload-artifact@v3
      with:
        name: build-distribution
        path: ./build/
        if-no-files-found: error
