apiVersion: v1
kind: Pod
spec:
  containers:
  - name: python-3-6
    image: python:3.6
    command:
    - sleep
    args:
    - infinity
  - name: python-3-7
    image: python:3.7
    command:
    - sleep
    args:
    - infinity
  - name: python-3-8
    image: python:3.8
    command:
    - sleep
    args:
    - infinity
  - name: python-3-9
    image: python:3.9
    command:
    - sleep
    args:
    - infinity
  - name: python-3-10
    image: python:3.10
    command:
    - sleep
    args:
    - infinity
  - name: pypy-3
    image: pypy:3.7-buster
    command:
    - sleep
    args:
    - infinity
## TODO: Faster builds with some cached artifacts.
##       mount a volume with the cached m2 folder in /var/lib/jenkins/.m2/repository
##       for instance https://github.com/jenkinsci/kubernetes-plugin/blob/master/examples/maven-with-cache.groovy
##       Maybe the infra folks already provide this caching!?
