export PYTEST_MARKER="-m pyodbc"
export DOCKER_DEPS="postgres"
export POSTGRES_HOST="postgres"
export POSTGRES_USER="postgres"
export POSTGRES_DB="elasticapm_test"
export POSTGRES_HOST="postgres"
export POSTGRES_PORT="5432"
