# This is the limited list of matrix builds in Windows, to be triggered on a PR basis
# The format is:
#  VERSION: Major.Minor python version.
#  WEBFRAMEWORK: What framework to be tested. String format.
#  ASYNCIO: Whether it's enabled or disabled. Boolean format.
#  DISTUTILS_USE_SDK: Whether configuring the environment to build with MSVC on a 64bit architecture. Binary format.
#

windows:
  - VERSION: "2.7"
    WEBFRAMEWORK: "none"
    ASYNCIO: "false"
    DISTUTILS_USE_SDK: "1"
