exclude:
  # Django
  - PYTHON_VERSION: python-2.7
    FRAMEWORK: django-2.0
  - PYTHON_VERSION: python-2.7
    FRAMEWORK: django-2.1
  - PYTHON_VERSION: python-2.7
    FRAMEWORK: django-2.2
  - PYTHON_VERSION: python-2.7
    FRAMEWORK: django-3.0
  - PYTHON_VERSION: python-2.7
    FRAMEWORK: django-master
  - PYTHON_VERSION: python-3.5
    FRAMEWORK: django-3.0
  - PYTHON_VERSION: python-3.7
    FRAMEWORK: django-1.11 # see https://code.djangoproject.com/ticket/28814
  - PYTHON_VERSION: pypy-2
    FRAMEWORK: django-2.0
  - PYTHON_VERSION: pypy-2
    FRAMEWORK: django-2.1
  - PYTHON_VERSION: pypy-2
    FRAMEWORK: django-2.2
  - PYTHON_VERSION: pypy-2
    FRAMEWORK: django-3.0
  - PYTHON_VERSION: pypy-2
    FRAMEWORK: django-master
  # Flask
  - PYTHON_VERSION: pypy-3
    FRAMEWORK: flask-0.11 # see https://github.com/pallets/flask/commit/6e46d0cd, 0.11.2 was never released
  # celery
  - PYTHON_VERSION: python-2.7
    FRAMEWORK: celery-3-django-2.0
  - PYTHON_VERSION: python-2.7
    FRAMEWORK: celery-4-django-2.0
  - PYTHON_VERSION: pypy-2
    FRAMEWORK: celery-3-django-2.0
  - PYTHON_VERSION: pypy-2
    FRAMEWORK: celery-4-django-2.0
  - PYTHON_VERSION: python-3.7
    FRAMEWORK: celery-3-django-1.11 # see https://code.djangoproject.com/ticket/28814
  # celery 4 doesn't currently work on Python 3.7, see https://github.com/celery/celery/issues/4500
  - PYTHON_VERSION: python-3.7
    FRAMEWORK: celery-4-django-2.0
  - PYTHON_VERSION: python-3.7
    FRAMEWORK: celery-4-django-1.11
  - PYTHON_VERSION: python-3.7
    FRAMEWORK: celery-4-flask-1.0
  - PYTHON_VERSION: python-3.8
    FRAMEWORK: celery-4-django-2.0
  - PYTHON_VERSION: python-3.8
    FRAMEWORK: celery-4-django-1.11
  - PYTHON_VERSION: python-3.8
    FRAMEWORK: celery-4-flask-1.0
  - PYTHON_VERSION: python-3.9-rc
    FRAMEWORK: celery-4-django-2.0
  - PYTHON_VERSION: python-3.9-rc
    FRAMEWORK: celery-4-django-1.11
  - PYTHON_VERSION: python-3.9-rc
    FRAMEWORK: celery-4-flask-1.0
  # requests
  - PYTHON_VERSION: python-3.5
    FRAMEWORK: requests-1.2
  - PYTHON_VERSION: python-3.6
    FRAMEWORK: requests-1.2
  - PYTHON_VERSION: python-3.7
    FRAMEWORK: requests-1.2
  - PYTHON_VERSION: python-3.8
    FRAMEWORK: requests-1.2
  - PYTHON_VERSION: python-3.9-rc
    FRAMEWORK: requests-1.2
  - PYTHON_VERSION: pypy-3
    FRAMEWORK: requests-1.2
  # pymongo
  - PYTHON_VERSION: python-3.5
    FRAMEWORK: pymongo-3.0
  - PYTHON_VERSION: python-3.6
    FRAMEWORK: pymongo-3.0
  - PYTHON_VERSION: python-3.7
    FRAMEWORK: pymongo-3.0
  - PYTHON_VERSION: python-3.8
    FRAMEWORK: pymongo-3.0
  - PYTHON_VERSION: python-3.9-rc
    FRAMEWORK: pymongo-3.0
  - PYTHON_VERSION: python-3.6
    FRAMEWORK: pymongo-3.1
  - PYTHON_VERSION: python-3.7
    FRAMEWORK: pymongo-3.1
  - PYTHON_VERSION: python-3.8
    FRAMEWORK: pymongo-3.1
  - PYTHON_VERSION: python-3.9-rc
    FRAMEWORK: pymongo-3.1
  - PYTHON_VERSION: python-3.6
    FRAMEWORK: pymongo-3.2
  - PYTHON_VERSION: python-3.7
    FRAMEWORK: pymongo-3.2
  - PYTHON_VERSION: python-3.8
    FRAMEWORK: pymongo-3.2
  - PYTHON_VERSION: python-3.9-rc
    FRAMEWORK: pymongo-3.2
  - PYTHON_VERSION: python-3.6
    FRAMEWORK: pymongo-3.3
  - PYTHON_VERSION: python-3.7
    FRAMEWORK: pymongo-3.3
  - PYTHON_VERSION: python-3.8
    FRAMEWORK: pymongo-3.3
  - PYTHON_VERSION: python-3.9-rc
    FRAMEWORK: pymongo-3.3
  - PYTHON_VERSION: python-3.6
    FRAMEWORK: pymongo-3.4
  - PYTHON_VERSION: python-3.7
    FRAMEWORK: pymongo-3.4
  - PYTHON_VERSION: python-3.8
    FRAMEWORK: pymongo-3.4
  - PYTHON_VERSION: python-3.9-rc
    FRAMEWORK: pymongo-3.4
  - PYTHON_VERSION: pypy-3
    FRAMEWORK: pymongo-3.0
  # python-memcached
  - PYTHON_VERSION: python-3.5
    FRAMEWORK: memcached-1.51
  - PYTHON_VERSION: python-3.6
    FRAMEWORK: memcached-1.51
  - PYTHON_VERSION: python-3.7
    FRAMEWORK: memcached-1.51
  - PYTHON_VERSION: python-3.8
    FRAMEWORK: memcached-1.51
  - PYTHON_VERSION: python-3.9-rc
    FRAMEWORK: memcached-1.51
  - PYTHON_VERSION: pypy-3
    FRAMEWORK: memcached-1.51
  # pymssql
  - PYTHON_VERSION: pypy-2 # currently fails with error on pypy2
    FRAMEWORK: pymssql-newest
  - PYTHON_VERSION: pypy-3 # currently fails with error on pypy3
    FRAMEWORK: pymssql-newest
  - PYTHON_VERSION: python-3.6 # currently fails with error on python 3.6 due to cython issues
    FRAMEWORK: pymssql-newest
  - PYTHON_VERSION: python-3.7 # currently fails with error on python 3.7 due to cython issues
    FRAMEWORK: pymssql-newest
  - PYTHON_VERSION: python-3.8 # currently fails with error on python 3.8 due to cython issues
    FRAMEWORK: pymssql-newest
  - PYTHON_VERSION: python-3.9-rc # currently fails with error on python 3.8 due to cython issues
    FRAMEWORK: pymssql-newest
  # psycopg2
  - PYTHON_VERSION: python-3.8 # see https://github.com/psycopg/psycopg2/issues/858
    FRAMEWORK: psycopg2-2.7
  - PYTHON_VERSION: python-3.9-rc # see https://github.com/psycopg/psycopg2/issues/858
    FRAMEWORK: psycopg2-2.7
  # pyodbc
  - PYTHON_VERSION: pypy-2
    FRAMEWORK: pyodbc-newest
  - PYTHON_VERSION: pypy-3
    FRAMEWORK: pyodbc-newest
  # boto3
  - PYTHON_VERSION: python-3.6
    FRAMEWORK: boto3-1.0
  - PYTHON_VERSION: python-3.7
    FRAMEWORK: boto3-1.0
  - PYTHON_VERSION: python-3.8
    FRAMEWORK: boto3-1.0
  - PYTHON_VERSION: python-3.9-rc
    FRAMEWORK: boto3-1.0
  - PYTHON_VERSION: pypy-3
    FRAMEWORK: boto3-1.0
  # boto3 is currently not importable on Python 3.9, see https://github.com/boto/botocore/issues/2002
  - PYTHON_VERSION: python-3.9-rc
    FRAMEWORK: boto3-1.0
  - PYTHON_VERSION: python-3.9-rc
    FRAMEWORK: boto3-1.5
  - PYTHON_VERSION: python-3.9-rc
    FRAMEWORK: boto3-1.6
  - PYTHON_VERSION: python-3.9-rc
    FRAMEWORK: boto3-newest
  # opentracing
  - PYTHON_VERSION: python-3.3
    FRAMEWORK: opentracing-newest
  # eventlet
  - PYTHON_VERSION: pypy-2  #currently fails on pypy2
    FRAMEWORK: eventlet-newest
  # zerorpc - only run on py2
  - PYTHON_VERSION: pypy-3
    FRAMEWORK: zerorpc-0.4
  - PYTHON_VERSION: python-3.5
    FRAMEWORK: zerorpc-0.4
  - PYTHON_VERSION: python-3.6
    FRAMEWORK: zerorpc-0.4
  - PYTHON_VERSION: python-3.7
    FRAMEWORK: zerorpc-0.4
  - PYTHON_VERSION: python-3.8
    FRAMEWORK: zerorpc-0.4
  - PYTHON_VERSION: python-3.9-rc
    FRAMEWORK: zerorpc-0.4
  # gevent
  - PYTHON_VERSION: pypy-2  # see https://github.com/gevent/gevent/issues/1380, fix will be in gevent 1.5
    FRAMEWORK: gevent-newest
  # aiohttp client, only supported in Python 3.7+
  - PYTHON_VERSION: python-2.7
    FRAMEWORK: aiohttp-3.0
  - PYTHON_VERSION: pypy-2
    FRAMEWORK: aiohttp-3.0
  - PYTHON_VERSION: pypy-3
    FRAMEWORK: aiohttp-3.0
  - PYTHON_VERSION: python-3.5
    FRAMEWORK: aiohttp-3.0
  - PYTHON_VERSION: python-3.6
    FRAMEWORK: aiohttp-3.0
  - PYTHON_VERSION: python-2.7
    FRAMEWORK: aiohttp-4.0
  - PYTHON_VERSION: pypy-2
    FRAMEWORK: aiohttp-4.0
  - PYTHON_VERSION: pypy-3
    FRAMEWORK: aiohttp-4.0
  - PYTHON_VERSION: python-3.5
    FRAMEWORK: aiohttp-4.0
  - PYTHON_VERSION: python-3.6
    FRAMEWORK: aiohttp-4.0
  - PYTHON_VERSION: python-2.7
    FRAMEWORK: aiohttp-newest
  - PYTHON_VERSION: pypy-2
    FRAMEWORK: aiohttp-newest
  - PYTHON_VERSION: pypy-3
    FRAMEWORK: aiohttp-newest
  - PYTHON_VERSION: python-3.5
    FRAMEWORK: aiohttp-newest
  - PYTHON_VERSION: python-3.6
    FRAMEWORK: aiohttp-newest
  # tornado, only supported in Python 3.7+
  - PYTHON_VERSION: python-2.7
    FRAMEWORK: tornado-newest
  - PYTHON_VERSION: pypy-2
    FRAMEWORK: tornado-newest
  - PYTHON_VERSION: pypy-3
    FRAMEWORK: tornado-newest
  - PYTHON_VERSION: python-3.5
    FRAMEWORK: tornado-newest
  - PYTHON_VERSION: python-3.6
    FRAMEWORK: tornado-newest
  # Starlette, only supported in python 3.7+
  - PYTHON_VERSION: python-2.7
    FRAMEWORK: starlette-0.13
  - PYTHON_VERSION: pypy-2
    FRAMEWORK: starlette-0.13
  - PYTHON_VERSION: pypy-3
    FRAMEWORK: starlette-0.13
  - PYTHON_VERSION: python-3.5
    FRAMEWORK: starlette-0.13
  - PYTHON_VERSION: python-3.6
    FRAMEWORK: starlette-0.13
  - PYTHON_VERSION: python-2.7
    FRAMEWORK: starlette-newest
  - PYTHON_VERSION: pypy-2
    FRAMEWORK: starlette-newest
  - PYTHON_VERSION: pypy-3
    FRAMEWORK: starlette-newest
  - PYTHON_VERSION: python-3.5
    FRAMEWORK: starlette-newest
  - PYTHON_VERSION: python-3.6
    FRAMEWORK: starlette-newest
  # aiopg
  - PYTHON_VERSION: python-2.7
    FRAMEWORK: aiopg-newest
  - PYTHON_VERSION: pypy-2
    FRAMEWORK: aiopg-newest
  - PYTHON_VERSION: pypy-3
    FRAMEWORK: aiopg-newest
  - PYTHON_VERSION: python-3.5
    FRAMEWORK: aiopg-newest
  - PYTHON_VERSION: python-3.6
    FRAMEWORK: aiopg-newest
  # asyncpg
  - PYTHON_VERSION: python-2.7
    FRAMEWORK: asyncpg-newest
  - PYTHON_VERSION: pypy-2
    FRAMEWORK: asyncpg-newest
  - PYTHON_VERSION: pypy-3
    FRAMEWORK: asyncpg-newest
  - PYTHON_VERSION: python-3.5
    FRAMEWORK: asyncpg-newest
  - PYTHON_VERSION: python-3.6
    FRAMEWORK: asyncpg-newest
  # psutil
  - PYTHON_VERSION: pypy-2  #currently fails on pypy2 (https://github.com/giampaolo/psutil/issues/1659)
    FRAMEWORK: psutil-newest
  # httpx (python3.6+)
  - PYTHON_VERSION: pypy-2
    FRAMEWORK: httpx-0.12
  - PYTHON_VERSION: pypy-2
    FRAMEWORK: httpx-0.13
  - PYTHON_VERSION: pypy-2
    FRAMEWORK: httpx-0.14
  - PYTHON_VERSION: pypy-2
    FRAMEWORK: httpx-newest
  - PYTHON_VERSION: python-2.7
    FRAMEWORK: httpx-0.12
  - PYTHON_VERSION: python-2.7
    FRAMEWORK: httpx-0.13
  - PYTHON_VERSION: python-2.7
    FRAMEWORK: httpx-0.14
  - PYTHON_VERSION: python-2.7
    FRAMEWORK: httpx-newest
  - PYTHON_VERSION: python-3.5
    FRAMEWORK: httpx-0.12
  - PYTHON_VERSION: python-3.5
    FRAMEWORK: httpx-0.13
  - PYTHON_VERSION: python-3.5
    FRAMEWORK: httpx-0.14
  - PYTHON_VERSION: python-3.5
    FRAMEWORK: httpx-newest
