# This is the full list of matrix builds, to be triggered with a daily build
# or manually
FRAMEWORK:
  - none
  - django-1.8
  - django-1.11
  - django-2.0
  - django-2.1
  - django-2.2
  - django-3.0
#  - django-master
  - flask-0.10
  - flask-0.11
  - flask-0.12
  - flask-1.0
  - flask-1.1
  - celery-3-flask-1.0
  - celery-3-django-1.11
  - celery-3-django-2.0
  - celery-4-flask-1.0
  - celery-4-django-1.11
  - celery-4-django-2.0
  - opentracing-newest
  - opentracing-2.0
  - twisted-18
  - twisted-17
  - twisted-16
  - twisted-15
  - requests-newest
  - boto3-1.0
  - boto3-1.5
  - boto3-1.6
  - boto3-newest
  - pymongo-2.9
  - pymongo-3.0
  - pymongo-3.1
  - pymongo-3.2
  - pymongo-3.3
  - pymongo-3.4
  - pymongo-3.5
  - pymongo-newest
  - redis-2.8
  - redis-2.9
  - redis-newest
  - psycopg2-2.7
  - psycopg2-newest
  - pymssql-newest
  - memcached-1.51
  - memcached-newest
  - pylibmc-1.4
  - pylibmc-newest
  - cassandra-3.4
  - cassandra-newest
  - psutil-newest
  - psutil-5.0
  - psutil-4.0
  - eventlet-newest
  - elasticsearch-2
  - elasticsearch-5
  - elasticsearch-6
  - elasticsearch-7
  - gevent-newest
  - zerorpc-0.4
  - aiohttp-3.0
  - aiohttp-4.0
  - aiohttp-newest
  - aiopg-newest
  - tornado-newest
  - starlette-0.13
  - starlette-newest
  - pymemcache-3.0
  - pymemcache-newest
  - graphene-2
