exclude:
  # Django
  - PYTHON_VERSION: python-2.7
    FRAMEWORK: django-2.0
  - PYTHON_VERSION: python-2.7
    FRAMEWORK: django-2.1
  - PYTHON_VERSION: python-2.7
    FRAMEWORK: django-2.2
  - PYTHON_VERSION: python-2.7
    FRAMEWORK: django-master
  - PYTHON_VERSION: python-3.4
    FRAMEWORK: django-2.1
  - PYTHON_VERSION: python-3.4
    FRAMEWORK: django-2.2
  - PYTHON_VERSION: python-3.4
    FRAMEWORK: django-master
  - PYTHON_VERSION: python-3.7
    FRAMEWORK: django-1.11 # see https://code.djangoproject.com/ticket/28814
  - PYTHON_VERSION: pypy-2
    FRAMEWORK: django-2.0
  - PYTHON_VERSION: pypy-2
    FRAMEWORK: django-2.1
  - PYTHON_VERSION: pypy-2
    FRAMEWORK: django-2.2
  - PYTHON_VERSION: pypy-2
    FRAMEWORK: django-master
  # Flask
  - PYTHON_VERSION: pypy-3
    FRAMEWORK: flask-0.11 # see https://github.com/pallets/flask/commit/6e46d0cd, 0.11.2 was never released
  # celery
  - PYTHON_VERSION: python-2.7
    FRAMEWORK: celery-3-django-2.0
  - PYTHON_VERSION: python-2.7
    FRAMEWORK: celery-4-django-2.0
  - PYTHON_VERSION: pypy-2
    FRAMEWORK: celery-3-django-2.0
  - PYTHON_VERSION: pypy-2
    FRAMEWORK: celery-4-django-2.0
  - PYTHON_VERSION: python-3.7
    FRAMEWORK: celery-3-django-1.11 # see https://code.djangoproject.com/ticket/28814
  # celery 4 doesn't currently work on Python 3.7, see https://github.com/celery/celery/issues/4500
  - PYTHON_VERSION: python-3.7
    FRAMEWORK: celery-4-django-2.0
  - PYTHON_VERSION: python-3.7
    FRAMEWORK: celery-4-django-1.11
  - PYTHON_VERSION: python-3.7
    FRAMEWORK: celery-4-flask-1.0
  - PYTHON_VERSION: python-3.8-rc
    FRAMEWORK: celery-4-django-2.0
  - PYTHON_VERSION: python-3.8-rc
    FRAMEWORK: celery-4-django-1.11
  - PYTHON_VERSION: python-3.8-rc
    FRAMEWORK: celery-4-flask-1.0
  # requests
  - PYTHON_VERSION: python-3.4
    FRAMEWORK: requests-1.2
  - PYTHON_VERSION: python-3.5
    FRAMEWORK: requests-1.2
  - PYTHON_VERSION: python-3.6
    FRAMEWORK: requests-1.2
  - PYTHON_VERSION: python-3.7
    FRAMEWORK: requests-1.2
  - PYTHON_VERSION: python-3.8-rc
    FRAMEWORK: requests-1.2
  - PYTHON_VERSION: pypy-3
    FRAMEWORK: requests-1.2
  # pymongo
  - PYTHON_VERSION: python-3.5
    FRAMEWORK: pymongo-3.0
  - PYTHON_VERSION: python-3.6
    FRAMEWORK: pymongo-3.0
  - PYTHON_VERSION: python-3.7
    FRAMEWORK: pymongo-3.0
  - PYTHON_VERSION: python-3.8-rc
    FRAMEWORK: pymongo-3.0
  - PYTHON_VERSION: python-3.6
    FRAMEWORK: pymongo-3.1
  - PYTHON_VERSION: python-3.7
    FRAMEWORK: pymongo-3.1
  - PYTHON_VERSION: python-3.8-rc
    FRAMEWORK: pymongo-3.1
  - PYTHON_VERSION: python-3.6
    FRAMEWORK: pymongo-3.2
  - PYTHON_VERSION: python-3.7
    FRAMEWORK: pymongo-3.2
  - PYTHON_VERSION: python-3.8-rc
    FRAMEWORK: pymongo-3.2
  - PYTHON_VERSION: python-3.6
    FRAMEWORK: pymongo-3.3
  - PYTHON_VERSION: python-3.7
    FRAMEWORK: pymongo-3.3
  - PYTHON_VERSION: python-3.8-rc
    FRAMEWORK: pymongo-3.3
  - PYTHON_VERSION: python-3.6
    FRAMEWORK: pymongo-3.4
  - PYTHON_VERSION: python-3.7
    FRAMEWORK: pymongo-3.4
  - PYTHON_VERSION: python-3.8-rc
    FRAMEWORK: pymongo-3.4
  - PYTHON_VERSION: pypy-3
    FRAMEWORK: pymongo-3.0
  # psycopg2
  - PYTHON_VERSION: python-3.7
    FRAMEWORK: psycopg2-2.5
  - PYTHON_VERSION: python-3.7
    FRAMEWORK: psycopg2-2.6
  - PYTHON_VERSION: python-3.8-rc
    FRAMEWORK: psycopg2-2.5
  - PYTHON_VERSION: python-3.8-rc
    FRAMEWORK: psycopg2-2.6
  - PYTHON_VERSION: pypy-3
    FRAMEWORK: psycopg2-2.5
  - PYTHON_VERSION: pypy-3
    FRAMEWORK: psycopg2-2.6
  # python-memcached
  - PYTHON_VERSION: python-3.4
    FRAMEWORK: memcached-1.51
  - PYTHON_VERSION: python-3.5
    FRAMEWORK: memcached-1.51
  - PYTHON_VERSION: python-3.6
    FRAMEWORK: memcached-1.51
  - PYTHON_VERSION: python-3.7
    FRAMEWORK: memcached-1.51
  - PYTHON_VERSION: python-3.8-rc
    FRAMEWORK: memcached-1.51
  - PYTHON_VERSION: pypy-3
    FRAMEWORK: memcached-1.51
  # pymssql
  - PYTHON_VERSION: pypy-2 # currently fails with error on pypy2
    FRAMEWORK: pymssql-newest
  - PYTHON_VERSION: python-3.6 # currently fails with error on python 3.6 due to cython issues
    FRAMEWORK: pymssql-newest
  - PYTHON_VERSION: python-3.7 # currently fails with error on python 3.7 due to cython issues
    FRAMEWORK: pymssql-newest
  - PYTHON_VERSION: python-3.8-rc # currently fails with error on python 3.8 due to cython issues
    FRAMEWORK: pymssql-newest
  # pyodbc
  - PYTHON_VERSION: pypy-2
    FRAMEWORK: pyodbc-newest
  - PYTHON_VERSION: pypy-3
    FRAMEWORK: pyodbc-newest
  # boto3
  - PYTHON_VERSION: python-3.6
    FRAMEWORK: boto3-1.0
  - PYTHON_VERSION: python-3.7
    FRAMEWORK: boto3-1.0
  - PYTHON_VERSION: python-3.8-rc
    FRAMEWORK: boto3-1.0
  - PYTHON_VERSION: pypy-3
    FRAMEWORK: boto3-1.0
  # opentracing
  - PYTHON_VERSION: python-3.3
    FRAMEWORK: opentracing-newest
  # eventlet
  - PYTHON_VERSION: pypy-2  #currently fails on pypy2
    FRAMEWORK: eventlet-newest
