# this is a limited list of matrix builds to be used for PRs
# see .jenkins_framework_full.yml for a full list
FRAMEWORK:
  - none
  - django-1.11
  - django-2.0
  - django-2.2
  - django-3.0
  - flask-0.12
  - flask-1.1
  - opentracing-newest
  - twisted-18
  - celery-3-flask-1.0
  - celery-3-django-2.0
  - celery-4-flask-1.0
  - celery-4-django-2.0
  - requests-newest
  - boto3-newest
  - pymongo-newest
  - redis-newest
  - psycopg2-newest
  - pymssql-newest
  - pyodbc-newest
  - memcached-newest
  - pylibmc-newest
  - elasticsearch-2
  - elasticsearch-6
  - elasticsearch-7
  - cassandra-newest
  - psutil-newest
  - eventlet-newest
  - gevent-newest
  - zerorpc-0.4
  - mysql_connector-newest
  - pymysql-newest
  - mysqlclient-newest
  - aiohttp-newest
  - aiopg-newest
  - tornado-newest
  - starlette-newest
  - pymemcache-newest
