exclude:
  - VERSION: pypy-3 # pypy3 currently fails on CI, e.g. https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-python%2Fapm-agent-python-mbp/detail/PR-1099/2/pipeline#step-3497-log-1
    FRAMEWORK: none
  # Django
  # Django 4.0 requires Python 3.8+
  - VERSION: pypy-3 # current pypy-3 is compatible with Python 3.7
    FRAMEWORK: django-4.0
  - VERSION: python-3.6
    FRAMEWORK: django-4.0
  - VERSION: python-3.7
    FRAMEWORK: django-4.0
  - VERSION: pypy-3 # current pypy-3 is compatible with Python 3.7
    FRAMEWORK: celery-5-django-4
  - VERSION: python-3.6
    FRAMEWORK: celery-5-django-4
  - VERSION: python-3.7
    FRAMEWORK: celery-5-django-4
  # Flask
  - VERSION: pypy-3
    FRAMEWORK: flask-0.11 # see https://github.com/pallets/flask/commit/6e46d0cd, 0.11.2 was never released
  # Python 3.10 removed a bunch of classes from collections, now in collections.abc
  - VERSION: python-3.10
    FRAMEWORK: django-1.11
  - VERSION: python-3.10
    FRAMEWORK: django-2.0
  - VERSION: python-3.10
    FRAMEWORK: celery-4-django-2.0
  - VERSION: python-3.10
    FRAMEWORK: celery-4-django-1.11
  - VERSION: python-3.11 # cannot import name 'formatargspec' from 'inspect'
    FRAMEWORK: celery-4-flask-1.0
  - VERSION: python-3.11 # https://github.com/celery/billiard/issues/377
    FRAMEWORK: celery-5-flask-2
  - VERSION: python-3.11 # https://github.com/celery/billiard/issues/377
    FRAMEWORK: celery-5-django-3
  - VERSION: python-3.11 # https://github.com/celery/billiard/issues/377
    FRAMEWORK: celery-5-django-4
  - VERSION: python-3.12 # cannot import name 'formatargspec' from 'inspect'
    FRAMEWORK: celery-4-flask-1.0
  - VERSION: python-3.12 # https://github.com/celery/billiard/issues/377
    FRAMEWORK: celery-5-flask-2
  - VERSION: python-3.12 # https://github.com/celery/billiard/issues/377
    FRAMEWORK: celery-5-django-3
  - VERSION: python-3.12 # https://github.com/celery/billiard/issues/377
    FRAMEWORK: celery-5-django-4
  - VERSION: python-3.10
    FRAMEWORK: graphene-2
  - VERSION: python-3.10
    FRAMEWORK: aiohttp-3.0
  - VERSION: python-3.10
    FRAMEWORK: aiohttp-4.0
  - VERSION: python-3.10
    FRAMEWORK: cassandra-3.4
  - VERSION: python-3.10
    FRAMEWORK: pymongo-3.5
  - VERSION: python-3.11
    FRAMEWORK: django-1.11
  - VERSION: python-3.11
    FRAMEWORK: django-2.0
  - VERSION: python-3.11
    FRAMEWORK: django-2.1
  - VERSION: python-3.11
    FRAMEWORK: celery-4-django-2.0
  - VERSION: python-3.11
    FRAMEWORK: celery-4-django-1.11
  - VERSION: python-3.11
    FRAMEWORK: graphene-2
  - VERSION: python-3.11
    FRAMEWORK: aiohttp-3.0
  - VERSION: python-3.11
    FRAMEWORK: aiohttp-4.0
  - VERSION: python-3.11
    FRAMEWORK: cassandra-3.4
  - VERSION: python-3.11
    FRAMEWORK: pymongo-3.5
  - VERSION: python-3.12
    FRAMEWORK: django-1.11
  - VERSION: python-3.12
    FRAMEWORK: django-2.0
  - VERSION: python-3.12
    FRAMEWORK: django-2.1
  - VERSION: python-3.12
    FRAMEWORK: celery-4-django-2.0
  - VERSION: python-3.12
    FRAMEWORK: celery-4-django-1.11
  - VERSION: python-3.12
    FRAMEWORK: graphene-2
  - VERSION: python-3.12
    FRAMEWORK: aiohttp-3.0
  - VERSION: python-3.12
    FRAMEWORK: aiohttp-4.0
  - VERSION: python-3.12
    FRAMEWORK: cassandra-3.4
  - VERSION: python-3.12
    FRAMEWORK: pymongo-3.5
  # pymongo
  - VERSION: python-3.10
    FRAMEWORK: pymongo-3.1
  - VERSION: python-3.11
    FRAMEWORK: pymongo-3.1
  - VERSION: python-3.12
    FRAMEWORK: pymongo-3.1
  - VERSION: python-3.10
    FRAMEWORK: pymongo-3.2
  - VERSION: python-3.11
    FRAMEWORK: pymongo-3.2
  - VERSION: python-3.12
    FRAMEWORK: pymongo-3.2
  - VERSION: python-3.10
    FRAMEWORK: pymongo-3.3
  - VERSION: python-3.11
    FRAMEWORK: pymongo-3.3
  - VERSION: python-3.12
    FRAMEWORK: pymongo-3.3
  - VERSION: python-3.8
    FRAMEWORK: pymongo-3.4
  - VERSION: python-3.9
    FRAMEWORK: pymongo-3.4
  - VERSION: python-3.10
    FRAMEWORK: pymongo-3.4
  - VERSION: python-3.11
    FRAMEWORK: pymongo-3.4
  - VERSION: python-3.12
    FRAMEWORK: pymongo-3.4
  - VERSION: pypy-3
    FRAMEWORK: pymongo-3.0
  # pymssql
  - VERSION: pypy-3 # currently fails with error on pypy3
    FRAMEWORK: pymssql-newest
  - VERSION: python-3.6 # dropped support for py3.6
    FRAMEWORK: pymssql-newest
  # pyodbc
  - VERSION: pypy-3
    FRAMEWORK: pyodbc-newest
  # boto3
  - VERSION: python-3.10
    FRAMEWORK: boto3-1.5
  - VERSION: python-3.10
    FRAMEWORK: boto3-1.6
  - VERSION: python-3.11
    FRAMEWORK: boto3-1.5
  - VERSION: python-3.11
    FRAMEWORK: boto3-1.6
  - VERSION: python-3.12
    FRAMEWORK: boto3-1.5
  - VERSION: python-3.12
    FRAMEWORK: boto3-1.6
  # aiohttp client, only supported in Python 3.7+
  - VERSION: pypy-3
    FRAMEWORK: aiohttp-3.0
  - VERSION: python-3.6
    FRAMEWORK: aiohttp-3.0
  - VERSION: pypy-3
    FRAMEWORK: aiohttp-4.0
  - VERSION: python-3.6
    FRAMEWORK: aiohttp-4.0
  - VERSION: pypy-3
    FRAMEWORK: aiohttp-newest
  - VERSION: python-3.6
    FRAMEWORK: aiohttp-newest
  # tornado, only supported in Python 3.7+
  - VERSION: pypy-3
    FRAMEWORK: tornado-newest
  - VERSION: python-3.6
    FRAMEWORK: tornado-newest
  # Starlette, only supported in python 3.7+
  - VERSION: pypy-3
    FRAMEWORK: starlette-0.13
  - VERSION: python-3.6
    FRAMEWORK: starlette-0.13
  - VERSION: pypy-3
    FRAMEWORK: starlette-0.14
  - VERSION: python-3.6
    FRAMEWORK: starlette-0.14
  - VERSION: pypy-3
    FRAMEWORK: starlette-newest
  - VERSION: python-3.6
    FRAMEWORK: starlette-newest
  # aiopg
  - VERSION: pypy-3
    FRAMEWORK: aiopg-newest
  - VERSION: python-3.6
    FRAMEWORK: aiopg-newest
  # asyncpg
  - VERSION: pypy-3
    FRAMEWORK: asyncpg-newest
  - VERSION: python-3.6
    FRAMEWORK: asyncpg-newest
  # sanic
  - VERSION: pypy-3
    FRAMEWORK: sanic-newest
  - VERSION: pypy-3
    FRAMEWORK: sanic-20.12
  - VERSION: python-3.6
    FRAMEWORK: sanic-20.12
  - VERSION: python-3.6
    FRAMEWORK: sanic-newest
  - VERSION: pypy-3
    # aioredis
    FRAMEWORK: aioredis-newest
  - VERSION: python-3.6
    FRAMEWORK: aioredis-newest
  # aiomysql
  - VERSION: pypy-3
    FRAMEWORK: aiomysql-newest
  - VERSION: python-3.6
    FRAMEWORK: aiomysql-newest
  # aiobotocore
  - VERSION: pypy-3
    FRAMEWORK: aiobotocore-newest
  - VERSION: python-3.6
    FRAMEWORK: aiobotocore-newest
  # mysql-connector-python
  - VERSION: python-3.6
    FRAMEWORK: mysql_connector-newest
  # twisted
  - VERSION: python-3.11
    FRAMEWORK: twisted-18
  - VERSION: python-3.11
    FRAMEWORK: twisted-17
  - VERSION: python-3.11
    FRAMEWORK: twisted-16
  - VERSION: python-3.11
    FRAMEWORK: twisted-15
  - VERSION: python-3.12
    FRAMEWORK: twisted-18
  - VERSION: python-3.12
    FRAMEWORK: twisted-17
  - VERSION: python-3.12
    FRAMEWORK: twisted-16
  - VERSION: python-3.12
    FRAMEWORK: twisted-15
  # pylibmc
  - VERSION: python-3.11
    FRAMEWORK: pylibmc-1.4
  - VERSION: python-3.12
    FRAMEWORK: pylibmc-1.4
  # grpc
  - VERSION: python-3.6
    FRAMEWORK: grpc-newest
  - VERSION: python-3.7
    FRAMEWORK: grpc-1.24
  - VERSION: python-3.8
    FRAMEWORK: grpc-1.24
  - VERSION: python-3.9
    FRAMEWORK: grpc-1.24
  - VERSION: python-3.10
    FRAMEWORK: grpc-1.24
  - VERSION: python-3.11
    FRAMEWORK: grpc-1.24
  - VERSION: python-3.12
    FRAMEWORK: grpc-1.24
  - VERSION: python-3.7
    FRAMEWORK: flask-1.0
  - VERSION: python-3.7
    FRAMEWORK: flask-1.1
  - VERSION: python-3.7
    FRAMEWORK: jinja2-2
  - VERSION: python-3.7
    FRAMEWORK: celery-4-flask-1.0
  # TODO py3.12
  - VERSION: python-3.12
    FRAMEWORK: pymssql-newest  # no wheels available yet
  - VERSION: python-3.12
    FRAMEWORK: aiohttp-newest  # no wheels available yet
  - VERSION: python-3.12
    FRAMEWORK: elasticsearch-7  # relies on aiohttp
  - VERSION: python-3.12
    FRAMEWORK: elasticsearch-8  # relies on aiohttp
  - VERSION: python-3.12
    FRAMEWORK: aiobotocore-newest  # relies on aiohttp
  - VERSION: python-3.12
    FRAMEWORK: sanic-20.12  # no wheels available yet
  - VERSION: python-3.12
    FRAMEWORK: sanic-newest  # no wheels available yet
  - VERSION: python-3.12
    FRAMEWORK: kafka-python-newest  # https://github.com/dpkp/kafka-python/pull/2376
  - VERSION: python-3.12
    FRAMEWORK: pyodbc-newest  # error on wheel
  - VERSION: python-3.12
    FRAMEWORK: cassandra-newest  # c extension issue
