# This is the full list of matrix builds, to be triggered with a daily build
# or manually
FRAMEWORK:
  - none
  - django-1.11
  - django-2.0
  - django-2.1
  - django-2.2
  - django-3.0
  - django-3.1
  - django-3.2
  - django-4.0
  - django-4.2
  - django-5.0
    #  - django-master
  - flask-0.10
  - flask-0.11
  - flask-0.12
  - flask-1.0
  - flask-1.1
  - flask-2.0
  - flask-2.1
  - flask-2.2
  - flask-2.3
  - flask-3.0
  - jinja2-2
  - jinja2-3
  - celery-4-flask-1.0
  - celery-4-django-1.11
  - celery-4-django-2.0
  - celery-5-flask-2
  - celery-5-django-3
  - celery-5-django-4
  - celery-5-django-5
  - opentelemetry-newest
  - opentracing-newest
  - opentracing-2.0
  - twisted-newest
  - twisted-18
  - twisted-17
  - twisted-16
  - twisted-15
  - requests-newest
  - boto3-1.5
  - boto3-1.6
  - boto3-newest
  - pymongo-3.1
  - pymongo-3.2
  - pymongo-3.3
  - pymongo-3.4
  - pymongo-3.5
  - pymongo-newest
  - redis-3
  - redis-2
  - redis-newest
  - psycopg-newest
  - psycopg2-newest
  - pymssql-newest
  - memcached-newest
  - pylibmc-1.4
  - pylibmc-newest
  - cassandra-3.4
  - cassandra-newest
  - psutil-newest
  - psutil-5.0
  - psutil-4.0
  #- eventlet-newest
  - elasticsearch-2
  - elasticsearch-5
  - elasticsearch-6
  - elasticsearch-7
  - elasticsearch-8
  - gevent-newest
  - aiohttp-3.0
  - aiohttp-newest
  - aiopg-newest
  - asyncpg-0.28
  - asyncpg-newest
  - tornado-newest
  - starlette-0.13
  - starlette-0.14
  - starlette-newest
  - pymemcache-3.0
  - pymemcache-newest
  - graphene-2
  - httpx-0.13
  - httpx-0.14
  - httpx-0.21
  - httpx-newest
  - httplib2-newest
  - sanic-20.12
  - sanic-newest
  - aiobotocore-newest
  - kafka-python-newest
  - grpc-newest
  #- grpc-1.24 # This appears to have problems with python>3.6?
