[[asgi-middleware]]
=== ASGI Middleware

experimental::[]

Incorporating Elastic APM into your ASGI-based project only requires a few easy
steps.

NOTE: Several ASGI frameworks are supported natively.
Please check <<supported-technologies,Supported Technologies>> for more information

[float]
[[asgi-installation]]
==== Installation

Install the Elastic APM agent using pip:

[source,bash]
----
$ pip install elastic-apm
----

or add `elastic-apm` to your project's `requirements.txt` file.


[float]
[[asgi-setup]]
==== Setup

To set up the agent, you need to initialize it with appropriate settings.

The settings are configured either via environment variables, or as
initialization arguments.

You can find a list of all available settings in the
<<configuration, Configuration>> page.

To set up the APM agent, wrap your ASGI app with the `ASGITracingMiddleware`:

[source,python]
----
from elasticapm.contrib.asgi import ASGITracingMiddleware

app = MyGenericASGIApp()  # depending on framework

app = ASGITracingMiddleware(app)

----

Make sure to call <<api-set-transaction-name, `elasticapm.set_transaction_name()`>> with an appropriate transaction name in all your routes.

NOTE: Currently, the agent doesn't support automatic capturing of exceptions. 
You can follow progress on this issue on https://github.com/elastic/apm-agent-python/issues/1548[Github].

[float]
[[supported-python-versions]]
==== Supported Python versions

A list of supported <<supported-python,Python>> versions can be found on our <<supported-technologies,Supported Technologies>> page.

NOTE: Elastic APM only supports `asyncio` when using Python 3.7+
