[[getting-started]]

ifdef::env-github[]
NOTE: For the best reading experience,
please view this documentation at https://www.elastic.co/guide/en/apm/agent/python/current/getting-started.html[elastic.co]
endif::[]

== Getting started

Welcome to the APM Python agent docs.

The Elastic APM Python agent sends performance metrics and error logs to the APM Server.
It has built-in support for Django and Flask performance metrics and error logging, as well as generic support of other WSGI frameworks for error logging.

[float]
[[additional-components]]
=== Additional Components

APM Agents work in conjunction with the {apm-server-ref-v}/index.html[APM Server], {ref}/index.html[Elasticsearch], and {kibana-ref}/index.html[Kibana].
Please view the {apm-overview-ref-v}/index.html[APM Overview] for details on how these components work together.

[[framework-support]]
The Elastic APM Python Agent comes with support for the following frameworks:

 * <<django-support,Django>> 1.8 - 2.1
 * <<flask-support,Flask>> 0.10+
 
For other frameworks and custom Python code, the agent exposes a set of <<api,APIs>> for integration.

NOTE: The Elastic APM Python agent does currently not support asynchronous frameworks like Twisted or Tornado.