[[getting-started]]
== Introduction

The Elastic APM Python agent sends performance metrics and error logs to the APM Server.
It has built-in support for Django and Flask performance metrics and error logging, as well as generic support of other WSGI frameworks for error logging.

[float]
[[how-it-works]]
=== How does the Agent work?

The agent auto-instruments <<supported-technologies,supported technologies>> and records interesting events,
like HTTP requests and database queries. To do this, it {CONTENT_HERE}
This means that for the supported technologies, there are no code changes required.

The Agent automatically {CONTENT_HERE}

These events, called Transactions and Spans, are sent to the APM Server.
The APM Server converts them to a format suitable for Elasticsearch, and sends them to an Elasticsearch cluster.
You can then use the APM app in Kibana to gain insight into latency issues and error culprits within your application.

[float]
[[additional-components]]
=== Additional components

APM Agents work in conjunction with the {apm-server-ref-v}/index.html[APM Server], {ref}/index.html[Elasticsearch], and {kibana-ref}/index.html[Kibana].
Please view the {apm-overview-ref-v}/index.html[APM Overview] for details on how these components work together.
