= APM Python Agent Reference

:branch: current
include::{asciidoc-dir}/../../shared/attributes.asciidoc[]

[[getting-started]]
== Getting started

Welcome to the APM Python agent docs.

The Elastic APM Python agent sends performance metrics and error logs to the APM Server.
It has built-in support for Django and Flask performance metrics and error logging, as well as generic support of other WSGI frameworks for error logging.
The agent is only one of multiple components you need to get started with APM. Please also have a look at the documentation for

 * {apm-server-ref}/index.html[APM Server]
 * {ref}/index.html[Elasticsearch]

ifdef::env-github[]
NOTE: For the best reading experience, please head over to this document at https://www.elastic.co/guide/en/apm/agent/python/current/index.html[elastic.co]
endif::[]

[[framework-support]]
The Elastic APM Python Agent comes with support for the following frameworks:

 * <<django-support,Django>> 1.8 - 2.0
 * <<flask-support,Flask>> 0.10+
 
For other frameworks and custom Python code, the agent exposes a set of <<api,APIs>> for integration.

NOTE: The Elastic APM Python agent does currently not support asynchronous frameworks like Twisted or Tornado.

include::./configuration.asciidoc[Configuration]

include::./django.asciidoc[Django support]

include::./flask.asciidoc[Flask support]

[[advanced-topics]]
== Advanced Topics
include::./custom-instrumentation.asciidoc[Custom Instrumentation]
include::./sanitizing-data.asciidoc[Sanitizing Data]
include::./run-tests-locally.asciidoc[Run Tests Locally]

include::./api.asciidoc[API documentation]
include::./tuning.asciidoc[Tuning and Overhead considerations]
