[[upgrading]]
== Upgrading

Upgrades between minor versions of the agent, like from 3.1 to 3.2 are always backwards compatible.
Upgrades that involve a major version bump often come with some backwards incompatible changes.

We highly recommend to always pin the version of `elastic-apm` in your `requirements.txt` or `Pipfile`.
This avoids automatic upgrades to potentially incompatible versions.

[float]
[[end-of-life-dates]]
=== End of life dates

We love all our products, but sometimes we must say goodbye to a release so that we can continue moving
forward on future development and innovation.
Our https://www.elastic.co/support/eol[End of life policy] defines how long a given release is considered supported,
as well as how long a release is considered still in active development or maintenance.

[[upgrading-6.x]]
=== Upgrading to version 6 of the agent

==== Python 2 no longer supported

Please upgrade to Python 3.6+ to continue to receive regular updates.

==== `SANITIZE_FIELD_NAMES` changes

If you are using a non-default `sanitize_field_names` config, please note
that your entries must be surrounded with stars (e.g. `*secret*`) in order to
maintain previous behavior.

==== Tags removed (in favor of labels)

Tags were deprecated in the 5.x release (in favor of labels). They have now been
removed.

[[upgrading-5.x]]
=== Upgrading to version 5 of the agent

==== APM Server 7.3 required for some features

APM Server and Kibana 7.3 introduced support for collecting breakdown metrics, and central configuration of APM agents.
To use these features, please update the Python agent to 5.0+ and APM Server / Kibana to 7.3+

==== Tags renamed to Labels

To better align with other parts of the Elastic Stack and the {ecs-ref}/index.html[Elastic Common Schema],
we renamed "tags" to "labels", and introduced limited support for typed labels.
While tag values were only allowed to be strings, label values can be strings, booleans, or numerical.

To benefit from this change, ensure that you run at least *APM Server 6.7*, and use `elasticapm.label()` instead of `elasticapm.tag()`.
The `tag()` API will continue to work as before, but emit a `DeprecationWarning`. It will be removed in 6.0 of the agent.

[[upgrading-4.x]]
=== Upgrading to version 4 of the agent

4.0 of the Elastic APM Python Agent comes with several backwards incompatible changes.

[[upgrading-4.x-apm-server]]
==== APM Server 6.5 required
This version of the agent is *only compatible with APM Server 6.5+*.
To upgrade, we recommend to first upgrade APM Server, and then the agent.
APM Server 6.5+ is backwards compatible with versions 2.x and 3.x of the agent.

[[upgrading-4.x-configuration]]
==== Configuration options

Several configuration options have been removed, or renamed

 * `flush_interval` has been removed
 * the `flush_interval` and `max_queue_size` settings have been removed.
 * new settings introduced: `api_request_time` and `api_request_size`.
 * Some settings now require a unit for duration or size. See <<config-format-size, size format>> and <<config-format-duration, duration format>>.

[[upgrading-4.x-processors]]
==== Processors

The method to write processors for sanitizing events has been changed.
It will now be called for every type of event (transactions, spans and errors),
unless the event types are limited using a decorator.
See <<sanitizing-data, Sanitizing data>> for more information.
