github:
  owner: "elastic"
  repository: "apm-agent-python"
  apm_repository: "apm"
  apm_data_repository: "apm-data"
  branch: "main"
specs:
  apm_data_path: "input/elasticapm/docs/spec/v2"
  apm_json_path: "tests/agents/json-specs"
  apm_gherkin_path: "tests/agents/gherkin-specs"
apm_agent:
  gherkin_specs_path: "tests/bdd/features"
  json_specs_path: "tests/upstream/json-specs"
  server_schema_specs_path: "tests/upstream/json-specs"