name: docs-cleanup

on:
  pull_request_target:
    types:
      - closed

jobs:
  docs-preview:
    uses: elastic/docs-builder/.github/workflows/preview-cleanup.yml@bd6fd6cbe87c8ec56a0817b7ac6a287c7f624de4 # main
    permissions:
      contents: none
      id-token: write
      deployments: write
