name: microbenchmark

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - '**.asciidoc'

# limit the access of the generated GITHUB_TOKEN
permissions:
  contents: read

jobs:
  microbenchmark:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: elastic/apm-pipeline-library/.github/actions/run-microbenchmark@current
        with:
          vault-url: ${{ secrets.VAULT_ADDR }}
          vault-role-id: ${{ secrets.VAULT_ROLE_ID }}
          vault-secret-id: ${{ secrets.VAULT_SECRET_ID }}
          slack-channel: "#apm-agent-python"
          script: .ci/bench.sh
          environments: |
            BRANCH_NAME=${{ github.ref_name }}
