name: release

on:
  push:
    branches:
      - "feat/trusted-publisher"

permissions:
  contents: read

jobs:
  test:
    uses: ./.github/workflows/test.yml

  packages:
    uses: ./.github/workflows/packages.yml

  publish-pypi:
    needs:
      - test
      - packages
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: packages
          path: dist
      - name: Upload
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
