name: test-release

on:
  workflow_call:
    inputs:
      full-matrix:
        description: "Run the full matrix"
        required: true
        type: boolean
      ref:
        description: "The git ref of elastic/apm-agent-python to run test workflow from."
        required: false
        type: string
      enabled:
        description: "Whether to run the workfow"
        required: true
        type: boolean
      skip-build:
        description: "Skip the build distribution step"
        required: false
        type: boolean
        default: false
  workflow_dispatch:
    inputs:
      full-matrix:
        description: "Run the full matrix"
        required: true
        type: boolean
      enabled:
        description: "Whether to run the workfow"
        required: true
        type: boolean
      skip-build:
        description: "Skip the build distribution step"
        required: false
        type: boolean
        default: false

jobs:
  test:
    if: ${{ inputs.enabled }}
    uses: ./.github/workflows/test.yml
    with:
      full-matrix: ${{ inputs.full-matrix }}
      skip-build: ${{ inputs.skip-build }}

  run-if-disabled:
    if: ${{ ! inputs.enabled }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "do something to help with the reusable workflows with needs"
